// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2OKVtUsPRASUqfUeRRFExWebcH0DNNQg',
    appId: '1:481262430344:web:66de6177b8a280600f973d',
    messagingSenderId: '481262430344',
    projectId: 'eduapp-7d130',
    authDomain: 'eduapp-7d130.firebaseapp.com',
    storageBucket: 'eduapp-7d130.appspot.com',
    measurementId: 'G-SEWVFEN4BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIf_n_dQpSmCTioUyyEGZGZX0zHqf4Xgw',
    appId: '1:481262430344:android:029a5b091e55a4e30f973d',
    messagingSenderId: '481262430344',
    projectId: 'eduapp-7d130',
    storageBucket: 'eduapp-7d130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa6m6_vvjcj7Wn4QVhoDv7WK6P24B8_fg',
    appId: '1:481262430344:ios:0b57918f9614aa2f0f973d',
    messagingSenderId: '481262430344',
    projectId: 'eduapp-7d130',
    storageBucket: 'eduapp-7d130.appspot.com',
    iosBundleId: 'com.hariapp.eduapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa6m6_vvjcj7Wn4QVhoDv7WK6P24B8_fg',
    appId: '1:481262430344:ios:fced3bfd5754f21c0f973d',
    messagingSenderId: '481262430344',
    projectId: 'eduapp-7d130',
    storageBucket: 'eduapp-7d130.appspot.com',
    iosBundleId: 'com.hariapp.eduapp.RunnerTests',
  );
}
